### ISSUE TITLE
Atoms and Buckets seem to shake while manipulating molecules in the play area

### ISSUE THREAD

**Issue by loganbraywork** [phetsims/build-a-molecule#202] opened 2020-07-01 22:05 UTC
**Test device**

Windows 10 laptop

**Operating System**

Windows 10 v. 1903

**Browser**

Edge  v.83.0.478.56

**Problem description**

For https://github.com/phetsims/QA/issues/509

Appears on Chrome as well. Does NOT appear in Firefox. Atoms in the buckets in the Playground screen seem to jump or shake when molecules or atoms are manipulated in the play area. I've noticed that this seems to occur when the atoms are moved while in the upper half of the play area, as opposed to the lower half.

**Steps to reproduce**

1. Enter the Playground screen
2. Using the arrows next to the buckets, switch to the 5th set of buckets (featuring only 1 phosphorus)
3. Remove the phosphorus from the bucket and drag it around the upper half of the play area

**Visuals**

![2020-07-01BldMlclAtomJumping](https://user-images.githubusercontent.com/54685448/86295712-76cee780-bbb4-11ea-84db-84ef6a87c5fc.gif)

Troubleshooting information:
!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.1/phet/build-a-molecule_all_phet.html
Version: 1.0.0-rc.1 2020-06-19 20:40:00 UTC
Features missing: touch
Flags: pixelRatioScaling
User Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/83.0.4103.116 Safari/537.36 Edg/83.0.478.56
Language: en-US
Window: 1313x647
Pixel Ratio: 1.4625000953674316/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 30 uniform: 4095
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 32)
Max viewport: 32767x32767
OES_texture_float: true
Dependencies JSON: {}

**Comment by Denz1994** [comment] 2020-07-16 15:01
Initial investigating doesn't indicate that atom positions, destinations, or atomNode translations aren't being updated while in the buckets. Also, this isn't just related to the buckets or atoms because the carousel, page navigation, and resetAllButton is also shaking in the gif. The next steps would be to check for changing Bounds (carousel,layout bounds and play area).

As a side note, I can't replicate this buggy behavior on my local machine (windows or mac).

**Comment by Denz1994** [comment] 2020-07-27 13:43
I've exhausted checking for bounds or position changes of all view components on the playground screen while dragging items as described above. These values aren't changing and I can't replicate this behavior locally. I've also tried replicating on two mobile devices, two windows devices, and my primary dev machine (MacBook) with no success. If this was a performance issue it should be evident on a mobile device.

Passing this back to QA to make sure this can still be replicated. Perhaps there is a different set of instructions to follow to reproduce this bug. I find it odd that this wasn't caught in https://github.com/phetsims/QA/issues/506 being that this dev-test came right before this RC with little code changes in between. 

@KatieWoe Can this be tested again to verify this can be replicated with the above steps? I'm having trouble reproducing this bug.

**Comment by loganbraywork** [comment] 2020-07-27 20:24
The laptop I used for testing in which I found this issue has a large screen. This may be the cause of the shaking. I did test this issue when the window is not fully expanded, and the same shaking does occur.

**Comment by KatieWoe** [comment] 2020-07-28 16:43
I looked on master on Win 10 Chrome and didn't see anything. But also can't really see it in the gif. As such I'm going to assign @loganbraywork to work with @Denz1994 on this.

**Comment by Denz1994** [comment] 2020-08-26 16:28
Should be verified by the latest [RC](https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.2/phet/build-a-molecule_en_phet.html).

**Comment by ariel-phet** [comment] 2020-08-26 17:01
I checked this on Win 10 edge, not seeing anything. Could be device specific, since neither myself, @Denz1994 @KatieWoe has seen this, it is not worth pursuing further. Closing

**Closed by ariel-phet** 2020-08-26 17:01 UTC
Labels: status:ready-for-qa, type:bug
