### ISSUE TITLE
Startup layout bug - prevents animation frame

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#29] opened 2013-10-16 10:19 UTC
Seems potentially linked to an order issue or possibly require.js. Seems to happen occasionally when opening a non-cached version.
![bam-ipad-startup](https://f.cloud.github.com/assets/480878/1341550/883dc774-364c-11e3-8f97-537d2b75e647.PNG)

**Comment by Denz1994** [comment] 2019-11-20 13:31
Similarly to https://github.com/phetsims/build-a-molecule/issues/35#issuecomment-556002773, I can't reproduce this issue. The latest versions =seem to be opening just fine without animation hiccups. However, this is present in [0.0.0-dev.11](https://phet-dev.colorado.edu/html/build-a-molecule/0.0.0-dev.11/build-a-molecule_en.html).

Closing.

**Closed by Denz1994** 2019-11-20 13:31 UTC
Labels: type:bug
