### ISSUE TITLE
Sim is non-interactive while loading another sim in another tab.

### ISSUE THREAD

**Issue by KatieWoe** [phetsims/build-a-molecule#213] opened 2020-09-30 18:48 UTC
**Test device**
Macbook Air
**Operating System**
MacOS 10.15.7
**Browser**
Chrome 85.0.4183.121
**Problem description**
For https://github.com/phetsims/QA/issues/550. Found while looking at https://github.com/phetsims/build-a-molecule/issues/203. I was unable to reproduce this when I tried on a few published sims and sims on master.
If you open the sim in two or three tabs, and the sim seems loaded in one but not yet the others, you will be unable to interact with the loaded sim until the others are loaded. The load time for BAM is also relatively slow, so it can easily seem like a problem.
**Steps to reproduce**
1. Open and load the sim in one tab.
2. When loaded, duplicate the tab once or twice.
3. While those tabs are loading, go back to the first tab and try to use the sim.

Troubleshooting information:

<details>

!!!!! DO NOT EDIT !!!!!
Name: ‪Build a Molecule‬
URL: https://phet-dev.colorado.edu/html/build-a-molecule/1.0.0-rc.3/phet/build-a-molecule_all_phet.html
Version: 1.0.0-rc.3 2020-09-16 23:48:35 UTC
Features missing: applicationcache, applicationcache, touch
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/85.0.4183.121 Safari/537.36
Language: en-US
Window: 1347x686
Pixel Ratio: 1/1
WebGL: WebGL 1.0 (OpenGL ES 2.0 Chromium)
GLSL: WebGL GLSL ES 1.0 (OpenGL ES GLSL ES 1.0 Chromium)
Vendor: WebKit (WebKit WebGL)
Vertex: attribs: 16 varying: 15 uniform: 1024
Texture: size: 16384 imageUnits: 16 (vertex: 16, combined: 80)
Max viewport: 16384x16384
OES_texture_float: true
Dependencies JSON: {}

</details>

**Comment by arouinfar** [comment] 2020-09-30 22:43
@Denz1994 @KatieWoe I was unable to reproduce this on my Mac, which is running the same macOS and Chrome versions as the test device. I also tried Safari 14 for comparison.

Unless there is a way to reproduce this at least somewhat reliably, I'm inclined to defer.

**Comment by Denz1994** [comment] 2020-10-06 16:10
I'm also not able to reproduce consistently. Granted I'm running a Macbook Pro, but I'd agree to defer on this. Most of the performance leg work is done during the startup of the sim. On my machine, this caused the initially loaded sim to lag a bit, but not be completely non-interactive. I had a similar experience with Density. This seems like a more general problem related to sim performance with multiple tabs.

If this becomes an issue for users, we should investigate how to reduce start-up time in this sim or address how sims perform when multiple tabs are loading. Closing this one for now.

**Closed by Denz1994** 2020-10-06 16:10 UTC
Labels: type:bug
