### ISSUE TITLE
Work around Chrome not changing the cursor instantly without a mousemove

### ISSUE THREAD

**Issue by jonathanolson** [phetsims/build-a-molecule#2] opened 2013-09-11 02:13 UTC
See http://stackoverflow.com/questions/8720071/how-do-i-force-the-mouse-cursor-to-change-without-a-mouse-movement-in-javascript
which references https://code.google.com/p/chromium/issues/detail?id=26723 and https://code.google.com/p/chromium/issues/detail?id=20717

**Comment by Denz1994** [comment] 2019-11-20 17:16
I've been able to reproduce this by:

1. setting a query parameter to `screens=1`
2. hovering the cursor over a pickable object (resetAllButton)
3. resetting the browser page
4. before the sim loads, click the cursor (without moving) so the cursor icon changes to default

When the sim loads the cursor will be over a pickable object, but won't be a pointer icon.
This is still an issue for users posted to https://code.google.com/p/chromium/issues/detail?id=26723.

Being that this is a minor bug and requires a browser-specific workaround, I would vote to punt on this issue. I will leave for @ariel-phet to decide.

**Comment by Denz1994** [comment] 2019-11-20 19:51
@jonathanolson mentioned:
This is a `Scenery` specific issue. Because we have to monitor whether the cursor is over a touch area or not, `Scenery` must track the position of the cursor. It doesn't do this until the cursor has moved. This happens in other sims as well and isn't browser-specific.

**Comment by ariel-phet** [comment] 2020-01-30 06:39
Yes, agreed, this bug is of very minor (if any) concern. The user will move the cursor almost immediately upon interacting with the sim regardless.

Marking as `wontfix` and closing

**Closed** 2020-01-30 06:39 UTC
Labels: type:bug, type:wontfix
